### ISSUE TITLE
problem on building react-native project

### ISSUE THREAD

**Issue by sumanbogati** [mihirsoni/react-native-android-speech#1]
As you suggested I have done following in **MainActivity.java**

```
package com.mysound;
import android.os.Bundle;
import com.facebook.react.ReactActivity;
import com.facebook.react.LifecycleState;
import com.facebook.react.ReactInstanceManager;
import com.facebook.react.ReactRootView;
import com.facebook.react.modules.core.DefaultHardwareBackBtnHandler;
import com.facebook.react.shell.MainReactPackage;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "mysound";
    }

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mReactRootView = new ReactRootView(this);

        mReactInstanceManager = ReactInstanceManager.builder()
                .setApplication(getApplication())
                .setBundleAssetName("index.android.bundle")
                .setJSMainModuleName("index.android")
                .addPackage(new MainReactPackage())
                .addPackage(new RCTTextToSpeechModule())           // Add any extra modules here
                .setUseDeveloperSupport(BuildConfig.DEBUG)
                .setInitialLifecycleState(LifecycleState.RESUMED)
                .build();

        mReactRootView.startReactApplication(mReactInstanceManager, "YourProject", null);

        setContentView(mReactRootView);
    }  
}
```

After run the **react-native run-android** command, I got following error

![error3](https://cloud.githubusercontent.com/assets/1753974/16894380/524284a0-4b72-11e6-9193-2e6690d5b499.png)

How to fix this problem?

**Comment by mihirsoni** [comment]
@sumanbogati  It seems you have copied the entire MainActicty from the documentation. You just need to add `.addPackage(new RCTTextToSpeechModule())` in your Activity.

Also make sure you have added gradle dependency

**Comment by sumanbogati** [comment]
**@mihirsoni** how do I get this  `RCTTextToSpeechModule` module in my main activity **Mainactivity.java**  file as I have done `import com.facebook.react.RCTTextToSpeechModule;` in file does not work, my activity  **Mainactivity.java** file has something like 
`   

```
 package com.mysound;
import com.facebook.react.ReactActivity;

public class MainActivity extends ReactActivity {

/**
 * Returns the name of the main component registered from JavaScript.
 * This is used to schedule rendering of the component.
 */
@Override
protected String getMainComponentName() {
    return "mysound";
}
```

  }`

How do I add this `.addPackage(new RCTTextToSpeechModule())` in my activity file.

It will be great if there is any working example you can provide to me.

My react native version
`react-native-cli: 0.2.
react-native: 0.29.1`

**Comment by mihirsoni** [comment]
@sumanbogati  , Try to follow the steps mentioned in READ.ME in your project. You don't need to copy paste exactly what is there inside the documentation. Just follow and change accoridng to your project.

First you need to install the dependency from the gradle [setup](https://github.com/mihirsoni/react-native-android-speech/blob/master/README.md#setup)

**Comment by sumanbogati** [comment]
@mihirsoni, I have installed module by `npm install --save-dev react-native-android-speech` and configured the **setting.gradle** something like,

 **rootProject.name = 'mysound'
 include ':app'
 include ':react-native-android-speech'
 project(':react-native-android-speech').projectDir = new File(settingsDir, '../node_modules/react-native-android-speech')**

Now I don't know what content my activity file(**MainActivity.java**) should have, my react project name is **mysound**, the default content for this file is something like

_package com.mysound;
    import com.facebook.react.ReactActivity;
    public class MainActivity extends ReactActivity {
        /**
         * Returns the name of the main component registered from JavaScript.
         * This is used to schedule rendering of the component.
         */
        @Override
        protected String getMainComponentName() {
            return "mysound";
        }
    }_



Now please tell me what code exactly should be in activity file **MainActivity.java**

**Comment by mihirsoni** [comment]
Closing this, please let me know if face problem again.

**Comment by sumanbogati** [comment]
I can built your project successfully, however the text to speech not working, my **index.android.js** is something like

`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  Platform,
  TouchableHighlight,
  TouchableNativeFeedback 
} from 'react-native';


var tts = require('react-native-android-speech')

function buttonClicked () {
    tts.speak({
        text:'Please provide some text to speak.', // Mandatory
        pitch:1.5, // Optional Parameter to set the pitch of Speech,
        forceStop : false , //  Optional Parameter if true , it will stop TTS if it is already in process
        language : 'en' // Optional Paramenter Default is en you can provide any supported lang by TTS
    }).then(isSpeaking=>{
        //Success Callback
        console.log(isSpeaking);
    }).catch(error=>{
        //Errror Callback
        console.log(error)
    });
    
     setTimeout(function(){ alert("finished here"); }, 3000);

}
class mysound extends Component {

  render() {
    var TouchableElement = TouchableHighlight;
    if (Platform.OS === 'android') {
        TouchableElement = TouchableNativeFeedback;
    }
    return (
      <View style={styles.container}>
          <Text style={styles.welcome}>
            Tap me as fast as you can!
          </Text>

          <TouchableElement
            onPress={buttonClicked}>
            <View>
              <Text>Button!</Text>
            </View>
          </TouchableElement>
  </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});



AppRegistry.registerComponent('mysound', () => mysound);
`

Can you please suggest how this module will work?
